"""Alembic migration template."""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd4bf8eed9e09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_receipt',
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_type', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=True),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('result_ref_type', sa.Text(), nullable=True),
    sa.Column('result_ref_id', sa.Text(), nullable=True),
    sa.Column('safe_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('pk_command_receipt')),
    sa.UniqueConstraint('command_id', name=op.f('uq_command_receipt_command_id'))
    )
    op.create_table('domain_event',
    sa.Column('sequence', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_revision', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('causation_id', sa.Uuid(), nullable=True),
    sa.Column('actor_subject_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_domain_event')),
    sa.UniqueConstraint('event_id', name='uq_domain_event_event_id')
    )
    op.create_index('ix_domain_event_aggregate_sequence', 'domain_event', ['aggregate_type', 'aggregate_id', 'sequence'], unique=False)
    op.create_index('ix_domain_event_correlation', 'domain_event', ['correlation_id'], unique=False)
    op.create_index('ix_domain_event_tenant_sequence', 'domain_event', ['tenant_id', 'sequence'], unique=False)
    op.create_index('ix_domain_event_type_occurred', 'domain_event', ['event_type', 'occurred_at'], unique=False)
    op.create_table('investigation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('source_provider', sa.Text(), nullable=False),
    sa.Column('source_resource_type', sa.Text(), nullable=False),
    sa.Column('source_address_id', sa.Text(), nullable=False),
    sa.Column('source_business_id', sa.Text(), nullable=True),
    sa.Column('initiated_by_subject', sa.Text(), nullable=False),
    sa.Column('initiated_by_display_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('current_plan_revision', sa.Integer(), nullable=False),
    sa.Column('budget_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('lock_version', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('response_proposal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("phase IS NULL OR phase IN ('HYDRATING','PLANNING','INVESTIGATING','VERIFYING','FINALIZING')", name=op.f('ck_investigation_investigation_phase_valid')),
    sa.CheckConstraint("status IN ('CREATED','RUNNING','WAITING_APPROVAL','EXECUTING_RESPONSE','COMPLETED','FAILED','CANCELLED')", name=op.f('ck_investigation_investigation_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation'))
    )
    op.create_index('ix_investigation_tenant_source', 'investigation', ['tenant_id', 'source_address_id'], unique=False)
    op.create_index('ix_investigation_tenant_status_created', 'investigation', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_index('uq_investigation_active_alert', 'investigation', ['tenant_id', 'source_provider', 'source_resource_type', 'source_address_id'], unique=True, postgresql_where=sa.text("status IN ('CREATED','RUNNING','WAITING_APPROVAL','EXECUTING_RESPONSE')"))
    op.create_table('outbox_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','PUBLISHED','FAILED')", name=op.f('ck_outbox_message_outbox_message_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_message')),
    sa.UniqueConstraint('event_id', 'destination', name='uq_outbox_event_destination')
    )
    op.create_index('ix_outbox_ready', 'outbox_message', ['status', 'available_at'], unique=False, postgresql_where="status IN ('PENDING','FAILED')")
    op.create_table('plan_step_state',
    sa.Column('plan_step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lock_version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','COMPLETED','SKIPPED')", name=op.f('ck_plan_step_state_plan_step_state_status_valid')),
    sa.PrimaryKeyConstraint('plan_step_id', name=op.f('pk_plan_step_state'))
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_provider', sa.Text(), nullable=False),
    sa.Column('source_operation', sa.Text(), nullable=False),
    sa.Column('source_resource_provider', sa.Text(), nullable=True),
    sa.Column('source_resource_type', sa.Text(), nullable=True),
    sa.Column('source_resource_address_id', sa.Text(), nullable=True),
    sa.Column('source_resource_business_id', sa.Text(), nullable=True),
    sa.Column('source_tool_invocation_id', sa.Uuid(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('observation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_authority', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.CheckConstraint("source_type IN ('HISIEM_ALERT','HISIEM_EVENT','HISIEM_LOG_SEARCH','HISIEM_ENTITY','THREAT_INTEL','KNOWLEDGE','SYSTEM')", name=op.f('ck_evidence_evidence_source_type_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_evidence_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('investigation_id', 'dedup_key', name='uq_evidence_investigation_dedup')
    )
    op.create_table('finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_finding_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding'))
    )
    op.create_table('hypothesis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.Column('assessment_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("current_status IN ('OPEN','SUPPORTED','CONTRADICTED','UNRESOLVED')", name=op.f('ck_hypothesis_hypothesis_status_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_hypothesis_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis'))
    )
    op.create_index('ix_hypothesis_investigation_status', 'hypothesis', ['investigation_id', 'current_status'], unique=False)
    op.create_table('investigation_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('verdict_disposition', sa.Text(), nullable=False),
    sa.Column('verdict_summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attack_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("verdict_disposition IN ('MALICIOUS','BENIGN','INCONCLUSIVE')", name=op.f('ck_investigation_result_investigation_result_verdict_valid')),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_investigation_result_investigation_result_confidence_range')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_investigation_result_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_result')),
    sa.UniqueConstraint('investigation_id', name=op.f('uq_investigation_result_investigation_id'))
    )
    op.create_table('orchestration_binding',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('graph_name', sa.Text(), nullable=False),
    sa.Column('graph_version', sa.Text(), nullable=False),
    sa.Column('state_schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_orchestration_binding_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_orchestration_binding')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_orchestration_binding_thread_id'))
    )
    op.create_table('plan_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('generator_kind', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("generator_kind IN ('system','llm','human')", name=op.f('ck_plan_revision_plan_revision_generator_kind_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_plan_revision_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_revision')),
    sa.UniqueConstraint('investigation_id', 'revision', name='uq_plan_revision_investigation_revision')
    )
    op.create_table('tool_invocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','SKIPPED')", name=op.f('ck_tool_invocation_tool_invocation_status_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_tool_invocation_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocation')),
    sa.UniqueConstraint('investigation_id', 'idempotency_key', name='uq_tool_invocation_investigation_key')
    )
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_finding_evidence_evidence_id_evidence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_finding_evidence_finding_id_finding'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('finding_id', 'evidence_id', name=op.f('pk_finding_evidence'))
    )
    op.create_table('hypothesis_assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','SUPPORTED','CONTRADICTED','UNRESOLVED')", name=op.f('ck_hypothesis_assessment_hypothesis_assessment_status_valid')),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], name=op.f('fk_hypothesis_assessment_hypothesis_id_hypothesis'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_hypothesis_assessment_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis_assessment')),
    sa.UniqueConstraint('hypothesis_id', 'revision', name='uq_hypothesis_assessment_hypothesis_revision')
    )
    op.create_table('investigation_result_finding',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_investigation_result_finding_finding_id_finding'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['investigation_result.id'], name=op.f('fk_investigation_result_finding_result_id_investigation_result'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('result_id', 'finding_id', name=op.f('pk_investigation_result_finding'))
    )
    op.create_table('plan_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_revision_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_revision_id'], ['plan_revision.id'], name=op.f('fk_plan_step_plan_revision_id_plan_revision'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_step')),
    sa.UniqueConstraint('plan_revision_id', 'ordinal', name='uq_plan_step_revision_ordinal'),
    sa.UniqueConstraint('plan_revision_id', 'step_key', name='uq_plan_step_revision_key')
    )
    op.create_table('response_proposal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('action_key', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_decision', sa.Text(), nullable=True),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('content_revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('lock_version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("policy_decision IS NULL OR policy_decision IN ('DENY','REQUIRE_APPROVAL')", name=op.f('ck_response_proposal_response_proposal_policy_valid')),
    sa.CheckConstraint("status IN ('CREATED','DENIED','WAITING_APPROVAL','APPROVED','REJECTED','SUBMITTED')", name=op.f('ck_response_proposal_response_proposal_status_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], name=op.f('fk_response_proposal_investigation_id_investigation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['investigation_result.id'], name=op.f('fk_response_proposal_result_id_investigation_result'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_proposal')),
    sa.UniqueConstraint('investigation_id', name='uq_response_proposal_investigation'),
    sa.UniqueConstraint('result_id', name='uq_response_proposal_result')
    )
    op.create_table('approval_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_content_revision', sa.Integer(), nullable=False),
    sa.Column('proposal_content_hash', sa.Text(), nullable=False),
    sa.Column('requested_reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['response_proposal.id'], name=op.f('fk_approval_request_proposal_id_response_proposal'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_request')),
    sa.UniqueConstraint('proposal_id', name=op.f('uq_approval_request_proposal_id'))
    )
    op.create_table('hypothesis_assessment_evidence',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.CheckConstraint("relation IN ('SUPPORTS','CONTRADICTS','CONTEXT')", name=op.f('ck_hypothesis_assessment_evidence_hae_relation_valid')),
    sa.ForeignKeyConstraint(['assessment_id'], ['hypothesis_assessment.id'], name=op.f('fk_hypothesis_assessment_evidence_assessment_id_hypothesis_assessment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_hypothesis_assessment_evidence_evidence_id_evidence'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assessment_id', 'evidence_id', 'relation', name=op.f('pk_hypothesis_assessment_evidence'))
    )
    op.create_table('response_execution_ref',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('submission_key', sa.Text(), nullable=False),
    sa.Column('last_observed_status', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['response_proposal.id'], name=op.f('fk_response_execution_ref_proposal_id_response_proposal'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('proposal_id', name=op.f('pk_response_execution_ref')),
    sa.UniqueConstraint('provider', 'execution_id', name='uq_response_execution_provider_id'),
    sa.UniqueConstraint('submission_key', name='uq_response_execution_submission_key')
    )
    op.create_table('response_proposal_evidence',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_response_proposal_evidence_evidence_id_evidence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['response_proposal.id'], name=op.f('fk_response_proposal_evidence_proposal_id_response_proposal'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('proposal_id', 'evidence_id', name=op.f('pk_response_proposal_evidence'))
    )
    op.create_table('response_proposal_target',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('address_id', sa.Text(), nullable=False),
    sa.Column('business_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['response_proposal.id'], name=op.f('fk_response_proposal_target_proposal_id_response_proposal'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('proposal_id', 'ordinal', name=op.f('pk_response_proposal_target')),
    sa.UniqueConstraint('proposal_id', 'provider', 'resource_type', 'address_id', name='uq_response_proposal_target_ref')
    )
    op.create_table('approval_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('actor_subject_id', sa.Text(), nullable=False),
    sa.Column('actor_tenant_id', sa.Text(), nullable=False),
    sa.Column('actor_display_name', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVE','REJECT')", name=op.f('ck_approval_decision_approval_decision_decision_valid')),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_request.id'], name=op.f('fk_approval_decision_approval_request_id_approval_request'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_decision')),
    sa.UniqueConstraint('approval_request_id', name=op.f('uq_approval_decision_approval_request_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_decision')
    op.drop_table('response_proposal_target')
    op.drop_table('response_proposal_evidence')
    op.drop_table('response_execution_ref')
    op.drop_table('hypothesis_assessment_evidence')
    op.drop_table('approval_request')
    op.drop_table('response_proposal')
    op.drop_table('plan_step')
    op.drop_table('investigation_result_finding')
    op.drop_table('hypothesis_assessment')
    op.drop_table('finding_evidence')
    op.drop_table('tool_invocation')
    op.drop_table('plan_revision')
    op.drop_table('orchestration_binding')
    op.drop_table('investigation_result')
    op.drop_index('ix_hypothesis_investigation_status', table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_table('finding')
    op.drop_table('evidence')
    op.drop_table('plan_step_state')
    op.drop_index('ix_outbox_ready', table_name='outbox_message', postgresql_where="status IN ('PENDING','FAILED')")
    op.drop_table('outbox_message')
    op.drop_index('uq_investigation_active_alert', table_name='investigation', postgresql_where=sa.text("status IN ('CREATED','RUNNING','WAITING_APPROVAL','EXECUTING_RESPONSE')"))
    op.drop_index('ix_investigation_tenant_status_created', table_name='investigation')
    op.drop_index('ix_investigation_tenant_source', table_name='investigation')
    op.drop_table('investigation')
    op.drop_index('ix_domain_event_type_occurred', table_name='domain_event')
    op.drop_index('ix_domain_event_tenant_sequence', table_name='domain_event')
    op.drop_index('ix_domain_event_correlation', table_name='domain_event')
    op.drop_index('ix_domain_event_aggregate_sequence', table_name='domain_event')
    op.drop_table('domain_event')
    op.drop_table('command_receipt')
    # ### end Alembic commands ###
